
package co.com.ic2.colciencias.scrapper.privado;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ScrapperColcienciasPrivado", targetNamespace = "http://privado.scrapper.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.ObjectFactory.class,
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.scrapper.privado.ObjectFactory.class
})
public interface ScrapperColcienciasPrivado {


    /**
     * 
     * @param identificacion
     * @param contrasena
     * @param paisNacimiento
     * @param tipoNacionalidad
     * @param nombre
     * @param idGrupo
     * @return
     *     returns co.com.ic2.colciencias.scrapper.privado.ExtraerGrupoInvestigacionObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "extraerGrupoInvestigacion", targetNamespace = "http://privado.scrapper.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.scrapper.privado.ExtraerGrupoInvestigacion")
    @ResponseWrapper(localName = "extraerGrupoInvestigacionResponse", targetNamespace = "http://privado.scrapper.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.scrapper.privado.ExtraerGrupoInvestigacionResponse")
    @Action(input = "http://privado.scrapper.colciencias.ic2.com.co/ScrapperColcienciasPrivado/extraerGrupoInvestigacionRequest", output = "http://privado.scrapper.colciencias.ic2.com.co/ScrapperColcienciasPrivado/extraerGrupoInvestigacionResponse")
    public ExtraerGrupoInvestigacionObject extraerGrupoInvestigacion(
        @WebParam(name = "tipoNacionalidad", targetNamespace = "")
        String tipoNacionalidad,
        @WebParam(name = "paisNacimiento", targetNamespace = "")
        String paisNacimiento,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "identificacion", targetNamespace = "")
        String identificacion,
        @WebParam(name = "contrasena", targetNamespace = "")
        String contrasena,
        @WebParam(name = "idGrupo", targetNamespace = "")
        int idGrupo);

}
