
package co.com.ic2.colciencias.scrapper.privado;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "scrapperColcienciasPrivado", targetNamespace = "http://privado.scrapper.colciencias.ic2.com.co/", wsdlLocation = "http://192.168.0.13:8084/scrapper_IC2_colciencias/ScrapperColcienciasPrivado?wsdl")
public class ScrapperColcienciasPrivado_Service
    extends Service
{

    private final static URL SCRAPPERCOLCIENCIASPRIVADO_WSDL_LOCATION;
    private final static WebServiceException SCRAPPERCOLCIENCIASPRIVADO_EXCEPTION;
    private final static QName SCRAPPERCOLCIENCIASPRIVADO_QNAME = new QName("http://privado.scrapper.colciencias.ic2.com.co/", "scrapperColcienciasPrivado");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.13:8084/scrapper_IC2_colciencias/ScrapperColcienciasPrivado?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCRAPPERCOLCIENCIASPRIVADO_WSDL_LOCATION = url;
        SCRAPPERCOLCIENCIASPRIVADO_EXCEPTION = e;
    }

    public ScrapperColcienciasPrivado_Service() {
        super(__getWsdlLocation(), SCRAPPERCOLCIENCIASPRIVADO_QNAME);
    }

    public ScrapperColcienciasPrivado_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCRAPPERCOLCIENCIASPRIVADO_QNAME, features);
    }

    public ScrapperColcienciasPrivado_Service(URL wsdlLocation) {
        super(wsdlLocation, SCRAPPERCOLCIENCIASPRIVADO_QNAME);
    }

    public ScrapperColcienciasPrivado_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCRAPPERCOLCIENCIASPRIVADO_QNAME, features);
    }

    public ScrapperColcienciasPrivado_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScrapperColcienciasPrivado_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScrapperColcienciasPrivado
     */
    @WebEndpoint(name = "ScrapperColcienciasPrivadoPort")
    public ScrapperColcienciasPrivado getScrapperColcienciasPrivadoPort() {
        return super.getPort(new QName("http://privado.scrapper.colciencias.ic2.com.co/", "ScrapperColcienciasPrivadoPort"), ScrapperColcienciasPrivado.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScrapperColcienciasPrivado
     */
    @WebEndpoint(name = "ScrapperColcienciasPrivadoPort")
    public ScrapperColcienciasPrivado getScrapperColcienciasPrivadoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://privado.scrapper.colciencias.ic2.com.co/", "ScrapperColcienciasPrivadoPort"), ScrapperColcienciasPrivado.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCRAPPERCOLCIENCIASPRIVADO_EXCEPTION!= null) {
            throw SCRAPPERCOLCIENCIASPRIVADO_EXCEPTION;
        }
        return SCRAPPERCOLCIENCIASPRIVADO_WSDL_LOCATION;
    }

}
