
package co.com.ic2.colciencias.scrapper.publico;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.GrupoInvestigacion;
import co.com.ic2.colciencias.gruplac.Investigador;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ScrapperColcienciasPublico", targetNamespace = "http://publico.scrapper.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.ObjectFactory.class,
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.scrapper.publico.ObjectFactory.class
})
public interface ScrapperColcienciasPublico {


    /**
     * 
     * @param investigador
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.GrupoInvestigacion>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "extraerGruposInvestigador", targetNamespace = "http://publico.scrapper.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.scrapper.publico.ExtraerGruposInvestigador")
    @ResponseWrapper(localName = "extraerGruposInvestigadorResponse", targetNamespace = "http://publico.scrapper.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.scrapper.publico.ExtraerGruposInvestigadorResponse")
    @Action(input = "http://publico.scrapper.colciencias.ic2.com.co/ScrapperColcienciasPublico/extraerGruposInvestigadorRequest", output = "http://publico.scrapper.colciencias.ic2.com.co/ScrapperColcienciasPublico/extraerGruposInvestigadorResponse")
    public List<GrupoInvestigacion> extraerGruposInvestigador(
        @WebParam(name = "Investigador", targetNamespace = "")
        Investigador investigador);

    /**
     * 
     * @param instituciones
     * @param lineasInvestigacion
     * @param integrantesDetalles
     * @param urlGruplac
     * @param integrantes
     * @param productos
     * @return
     *     returns co.com.ic2.colciencias.gruplac.GrupoInvestigacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "extraerGrupoInvestigacion", targetNamespace = "http://publico.scrapper.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.scrapper.publico.ExtraerGrupoInvestigacion")
    @ResponseWrapper(localName = "extraerGrupoInvestigacionResponse", targetNamespace = "http://publico.scrapper.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.scrapper.publico.ExtraerGrupoInvestigacionResponse")
    @Action(input = "http://publico.scrapper.colciencias.ic2.com.co/ScrapperColcienciasPublico/extraerGrupoInvestigacionRequest", output = "http://publico.scrapper.colciencias.ic2.com.co/ScrapperColcienciasPublico/extraerGrupoInvestigacionResponse")
    public GrupoInvestigacion extraerGrupoInvestigacion(
        @WebParam(name = "urlGruplac", targetNamespace = "")
        String urlGruplac,
        @WebParam(name = "instituciones", targetNamespace = "")
        boolean instituciones,
        @WebParam(name = "lineasInvestigacion", targetNamespace = "")
        boolean lineasInvestigacion,
        @WebParam(name = "integrantes", targetNamespace = "")
        boolean integrantes,
        @WebParam(name = "integrantesDetalles", targetNamespace = "")
        boolean integrantesDetalles,
        @WebParam(name = "productos", targetNamespace = "")
        boolean productos);

}
