
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "flujoRedNeuronal", targetNamespace = "ws.colciencias.ic2.com.co", wsdlLocation = "http://192.168.0.22:8082/flujoRedNeuronal?wsdl")
public class FlujoRedNeuronal
    extends Service
{

    private final static URL FLUJOREDNEURONAL_WSDL_LOCATION;
    private final static WebServiceException FLUJOREDNEURONAL_EXCEPTION;
    private final static QName FLUJOREDNEURONAL_QNAME = new QName("ws.colciencias.ic2.com.co", "flujoRedNeuronal");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.22:8082/flujoRedNeuronal?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLUJOREDNEURONAL_WSDL_LOCATION = url;
        FLUJOREDNEURONAL_EXCEPTION = e;
    }

    public FlujoRedNeuronal() {
        super(__getWsdlLocation(), FLUJOREDNEURONAL_QNAME);
    }

    public FlujoRedNeuronal(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLUJOREDNEURONAL_QNAME, features);
    }

    public FlujoRedNeuronal(URL wsdlLocation) {
        super(wsdlLocation, FLUJOREDNEURONAL_QNAME);
    }

    public FlujoRedNeuronal(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLUJOREDNEURONAL_QNAME, features);
    }

    public FlujoRedNeuronal(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlujoRedNeuronal(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceRedNeuronal
     */
    @WebEndpoint(name = "serviceRedNeuronalPort")
    public ServiceRedNeuronal getServiceRedNeuronalPort() {
        return super.getPort(new QName("ws.colciencias.ic2.com.co", "serviceRedNeuronalPort"), ServiceRedNeuronal.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceRedNeuronal
     */
    @WebEndpoint(name = "serviceRedNeuronalPort")
    public ServiceRedNeuronal getServiceRedNeuronalPort(WebServiceFeature... features) {
        return super.getPort(new QName("ws.colciencias.ic2.com.co", "serviceRedNeuronalPort"), ServiceRedNeuronal.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLUJOREDNEURONAL_EXCEPTION!= null) {
            throw FLUJOREDNEURONAL_EXCEPTION;
        }
        return FLUJOREDNEURONAL_WSDL_LOCATION;
    }

}
