
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "flujoScraperColciencias", targetNamespace = "ws.colciencias.ic2.com.co", wsdlLocation = "http://192.168.0.22:8082/flujoScraperColciencias?wsdl")
public class FlujoScraperColciencias
    extends Service
{

    private final static URL FLUJOSCRAPERCOLCIENCIAS_WSDL_LOCATION;
    private final static WebServiceException FLUJOSCRAPERCOLCIENCIAS_EXCEPTION;
    private final static QName FLUJOSCRAPERCOLCIENCIAS_QNAME = new QName("ws.colciencias.ic2.com.co", "flujoScraperColciencias");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.22:8082/flujoScraperColciencias?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLUJOSCRAPERCOLCIENCIAS_WSDL_LOCATION = url;
        FLUJOSCRAPERCOLCIENCIAS_EXCEPTION = e;
    }

    public FlujoScraperColciencias() {
        super(__getWsdlLocation(), FLUJOSCRAPERCOLCIENCIAS_QNAME);
    }

    public FlujoScraperColciencias(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLUJOSCRAPERCOLCIENCIAS_QNAME, features);
    }

    public FlujoScraperColciencias(URL wsdlLocation) {
        super(wsdlLocation, FLUJOSCRAPERCOLCIENCIAS_QNAME);
    }

    public FlujoScraperColciencias(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLUJOSCRAPERCOLCIENCIAS_QNAME, features);
    }

    public FlujoScraperColciencias(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlujoScraperColciencias(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceScraperColciencias
     */
    @WebEndpoint(name = "serviceScraperColcienciasPort")
    public ServiceScraperColciencias getServiceScraperColcienciasPort() {
        return super.getPort(new QName("ws.colciencias.ic2.com.co", "serviceScraperColcienciasPort"), ServiceScraperColciencias.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceScraperColciencias
     */
    @WebEndpoint(name = "serviceScraperColcienciasPort")
    public ServiceScraperColciencias getServiceScraperColcienciasPort(WebServiceFeature... features) {
        return super.getPort(new QName("ws.colciencias.ic2.com.co", "serviceScraperColcienciasPort"), ServiceScraperColciencias.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLUJOSCRAPERCOLCIENCIAS_EXCEPTION!= null) {
            throw FLUJOSCRAPERCOLCIENCIAS_EXCEPTION;
        }
        return FLUJOSCRAPERCOLCIENCIAS_WSDL_LOCATION;
    }

}
