
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceConsultoriaService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://10.8.0.3:8081/flujoConsultoria?wsdl")
public class IServiceConsultoriaService
    extends Service
{

    private final static URL ISERVICECONSULTORIASERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICECONSULTORIASERVICE_EXCEPTION;
    private final static QName ISERVICECONSULTORIASERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceConsultoriaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.8.0.3:8081/flujoConsultoria?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICECONSULTORIASERVICE_WSDL_LOCATION = url;
        ISERVICECONSULTORIASERVICE_EXCEPTION = e;
    }

    public IServiceConsultoriaService() {
        super(__getWsdlLocation(), ISERVICECONSULTORIASERVICE_QNAME);
    }

    public IServiceConsultoriaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICECONSULTORIASERVICE_QNAME, features);
    }

    public IServiceConsultoriaService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICECONSULTORIASERVICE_QNAME);
    }

    public IServiceConsultoriaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICECONSULTORIASERVICE_QNAME, features);
    }

    public IServiceConsultoriaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceConsultoriaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceConsultoria
     */
    @WebEndpoint(name = "serviceConsultoriaPort")
    public ServiceConsultoria getServiceConsultoriaPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceConsultoriaPort"), ServiceConsultoria.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceConsultoria
     */
    @WebEndpoint(name = "serviceConsultoriaPort")
    public ServiceConsultoria getServiceConsultoriaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceConsultoriaPort"), ServiceConsultoria.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICECONSULTORIASERVICE_EXCEPTION!= null) {
            throw ISERVICECONSULTORIASERVICE_EXCEPTION;
        }
        return ISERVICECONSULTORIASERVICE_WSDL_LOCATION;
    }

}
