
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceInnovacionProcedimientoServicioService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://10.8.0.3:8081/flujoInnovacionProcedimientoServicio?wsdl")
public class IServiceInnovacionProcedimientoServicioService
    extends Service
{

    private final static URL ISERVICEINNOVACIONPROCEDIMIENTOSERVICIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICEINNOVACIONPROCEDIMIENTOSERVICIOSERVICE_EXCEPTION;
    private final static QName ISERVICEINNOVACIONPROCEDIMIENTOSERVICIOSERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceInnovacionProcedimientoServicioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.8.0.3:8081/flujoInnovacionProcedimientoServicio?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICEINNOVACIONPROCEDIMIENTOSERVICIOSERVICE_WSDL_LOCATION = url;
        ISERVICEINNOVACIONPROCEDIMIENTOSERVICIOSERVICE_EXCEPTION = e;
    }

    public IServiceInnovacionProcedimientoServicioService() {
        super(__getWsdlLocation(), ISERVICEINNOVACIONPROCEDIMIENTOSERVICIOSERVICE_QNAME);
    }

    public IServiceInnovacionProcedimientoServicioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICEINNOVACIONPROCEDIMIENTOSERVICIOSERVICE_QNAME, features);
    }

    public IServiceInnovacionProcedimientoServicioService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICEINNOVACIONPROCEDIMIENTOSERVICIOSERVICE_QNAME);
    }

    public IServiceInnovacionProcedimientoServicioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICEINNOVACIONPROCEDIMIENTOSERVICIOSERVICE_QNAME, features);
    }

    public IServiceInnovacionProcedimientoServicioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceInnovacionProcedimientoServicioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceInnovacionProcedimientoServicio
     */
    @WebEndpoint(name = "serviceInnovacionProcedimientoServicioPort")
    public ServiceInnovacionProcedimientoServicio getServiceInnovacionProcedimientoServicioPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceInnovacionProcedimientoServicioPort"), ServiceInnovacionProcedimientoServicio.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceInnovacionProcedimientoServicio
     */
    @WebEndpoint(name = "serviceInnovacionProcedimientoServicioPort")
    public ServiceInnovacionProcedimientoServicio getServiceInnovacionProcedimientoServicioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceInnovacionProcedimientoServicioPort"), ServiceInnovacionProcedimientoServicio.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICEINNOVACIONPROCEDIMIENTOSERVICIOSERVICE_EXCEPTION!= null) {
            throw ISERVICEINNOVACIONPROCEDIMIENTOSERVICIOSERVICE_EXCEPTION;
        }
        return ISERVICEINNOVACIONPROCEDIMIENTOSERVICIOSERVICE_WSDL_LOCATION;
    }

}
