
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceAsesoriaProgramaOndasService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://192.168.0.14:8081/flujoAsesoriaProgramaOndas?wsdl")
public class IServiceAsesoriaProgramaOndasService
    extends Service
{

    private final static URL ISERVICEASESORIAPROGRAMAONDASSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICEASESORIAPROGRAMAONDASSERVICE_EXCEPTION;
    private final static QName ISERVICEASESORIAPROGRAMAONDASSERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceAsesoriaProgramaOndasService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.14:8081/flujoAsesoriaProgramaOndas?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICEASESORIAPROGRAMAONDASSERVICE_WSDL_LOCATION = url;
        ISERVICEASESORIAPROGRAMAONDASSERVICE_EXCEPTION = e;
    }

    public IServiceAsesoriaProgramaOndasService() {
        super(__getWsdlLocation(), ISERVICEASESORIAPROGRAMAONDASSERVICE_QNAME);
    }

    public IServiceAsesoriaProgramaOndasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICEASESORIAPROGRAMAONDASSERVICE_QNAME, features);
    }

    public IServiceAsesoriaProgramaOndasService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICEASESORIAPROGRAMAONDASSERVICE_QNAME);
    }

    public IServiceAsesoriaProgramaOndasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICEASESORIAPROGRAMAONDASSERVICE_QNAME, features);
    }

    public IServiceAsesoriaProgramaOndasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceAsesoriaProgramaOndasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceAsesoriaProgramaOndas
     */
    @WebEndpoint(name = "serviceAsesoriaProgramaOndasPort")
    public ServiceAsesoriaProgramaOndas getServiceAsesoriaProgramaOndasPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceAsesoriaProgramaOndasPort"), ServiceAsesoriaProgramaOndas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceAsesoriaProgramaOndas
     */
    @WebEndpoint(name = "serviceAsesoriaProgramaOndasPort")
    public ServiceAsesoriaProgramaOndas getServiceAsesoriaProgramaOndasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceAsesoriaProgramaOndasPort"), ServiceAsesoriaProgramaOndas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICEASESORIAPROGRAMAONDASSERVICE_EXCEPTION!= null) {
            throw ISERVICEASESORIAPROGRAMAONDASSERVICE_EXCEPTION;
        }
        return ISERVICEASESORIAPROGRAMAONDASSERVICE_WSDL_LOCATION;
    }

}
