
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceParticipacionCiudadanaProyectoCTIService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://192.168.0.14:8081/flujoParticipacionCiudadanaProyectoCTI?wsdl")
public class IServiceParticipacionCiudadanaProyectoCTIService
    extends Service
{

    private final static URL ISERVICEPARTICIPACIONCIUDADANAPROYECTOCTISERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICEPARTICIPACIONCIUDADANAPROYECTOCTISERVICE_EXCEPTION;
    private final static QName ISERVICEPARTICIPACIONCIUDADANAPROYECTOCTISERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceParticipacionCiudadanaProyectoCTIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.14:8081/flujoParticipacionCiudadanaProyectoCTI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICEPARTICIPACIONCIUDADANAPROYECTOCTISERVICE_WSDL_LOCATION = url;
        ISERVICEPARTICIPACIONCIUDADANAPROYECTOCTISERVICE_EXCEPTION = e;
    }

    public IServiceParticipacionCiudadanaProyectoCTIService() {
        super(__getWsdlLocation(), ISERVICEPARTICIPACIONCIUDADANAPROYECTOCTISERVICE_QNAME);
    }

    public IServiceParticipacionCiudadanaProyectoCTIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICEPARTICIPACIONCIUDADANAPROYECTOCTISERVICE_QNAME, features);
    }

    public IServiceParticipacionCiudadanaProyectoCTIService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICEPARTICIPACIONCIUDADANAPROYECTOCTISERVICE_QNAME);
    }

    public IServiceParticipacionCiudadanaProyectoCTIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICEPARTICIPACIONCIUDADANAPROYECTOCTISERVICE_QNAME, features);
    }

    public IServiceParticipacionCiudadanaProyectoCTIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceParticipacionCiudadanaProyectoCTIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceParticipacionCiudadanaProyectoCTI
     */
    @WebEndpoint(name = "serviceParticipacionCiudadanaProyectoCTIPort")
    public ServiceParticipacionCiudadanaProyectoCTI getServiceParticipacionCiudadanaProyectoCTIPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceParticipacionCiudadanaProyectoCTIPort"), ServiceParticipacionCiudadanaProyectoCTI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceParticipacionCiudadanaProyectoCTI
     */
    @WebEndpoint(name = "serviceParticipacionCiudadanaProyectoCTIPort")
    public ServiceParticipacionCiudadanaProyectoCTI getServiceParticipacionCiudadanaProyectoCTIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceParticipacionCiudadanaProyectoCTIPort"), ServiceParticipacionCiudadanaProyectoCTI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICEPARTICIPACIONCIUDADANAPROYECTOCTISERVICE_EXCEPTION!= null) {
            throw ISERVICEPARTICIPACIONCIUDADANAPROYECTOCTISERVICE_EXCEPTION;
        }
        return ISERVICEPARTICIPACIONCIUDADANAPROYECTOCTISERVICE_WSDL_LOCATION;
    }

}
