
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceRedConocimientoService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://10.8.0.4:8081/flujoRedConocimiento?wsdl")
public class IServiceRedConocimientoService
    extends Service
{

    private final static URL ISERVICEREDCONOCIMIENTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICEREDCONOCIMIENTOSERVICE_EXCEPTION;
    private final static QName ISERVICEREDCONOCIMIENTOSERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceRedConocimientoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.8.0.4:8081/flujoRedConocimiento?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICEREDCONOCIMIENTOSERVICE_WSDL_LOCATION = url;
        ISERVICEREDCONOCIMIENTOSERVICE_EXCEPTION = e;
    }

    public IServiceRedConocimientoService() {
        super(__getWsdlLocation(), ISERVICEREDCONOCIMIENTOSERVICE_QNAME);
    }

    public IServiceRedConocimientoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICEREDCONOCIMIENTOSERVICE_QNAME, features);
    }

    public IServiceRedConocimientoService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICEREDCONOCIMIENTOSERVICE_QNAME);
    }

    public IServiceRedConocimientoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICEREDCONOCIMIENTOSERVICE_QNAME, features);
    }

    public IServiceRedConocimientoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceRedConocimientoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceRedConocimiento
     */
    @WebEndpoint(name = "serviceRedConocimientoPort")
    public ServiceRedConocimiento getServiceRedConocimientoPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceRedConocimientoPort"), ServiceRedConocimiento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceRedConocimiento
     */
    @WebEndpoint(name = "serviceRedConocimientoPort")
    public ServiceRedConocimiento getServiceRedConocimientoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceRedConocimientoPort"), ServiceRedConocimiento.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICEREDCONOCIMIENTOSERVICE_EXCEPTION!= null) {
            throw ISERVICEREDCONOCIMIENTOSERVICE_EXCEPTION;
        }
        return ISERVICEREDCONOCIMIENTOSERVICE_WSDL_LOCATION;
    }

}
