
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServicePrototipoIndustrialService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://10.8.0.3:8081/flujoPrototipoIndustrial?wsdl")
public class IServicePrototipoIndustrialService
    extends Service
{

    private final static URL ISERVICEPROTOTIPOINDUSTRIALSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICEPROTOTIPOINDUSTRIALSERVICE_EXCEPTION;
    private final static QName ISERVICEPROTOTIPOINDUSTRIALSERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServicePrototipoIndustrialService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.8.0.3:8081/flujoPrototipoIndustrial?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICEPROTOTIPOINDUSTRIALSERVICE_WSDL_LOCATION = url;
        ISERVICEPROTOTIPOINDUSTRIALSERVICE_EXCEPTION = e;
    }

    public IServicePrototipoIndustrialService() {
        super(__getWsdlLocation(), ISERVICEPROTOTIPOINDUSTRIALSERVICE_QNAME);
    }

    public IServicePrototipoIndustrialService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICEPROTOTIPOINDUSTRIALSERVICE_QNAME, features);
    }

    public IServicePrototipoIndustrialService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICEPROTOTIPOINDUSTRIALSERVICE_QNAME);
    }

    public IServicePrototipoIndustrialService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICEPROTOTIPOINDUSTRIALSERVICE_QNAME, features);
    }

    public IServicePrototipoIndustrialService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServicePrototipoIndustrialService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicePrototipoIndustrial
     */
    @WebEndpoint(name = "servicePrototipoIndustrialPort")
    public ServicePrototipoIndustrial getServicePrototipoIndustrialPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "servicePrototipoIndustrialPort"), ServicePrototipoIndustrial.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePrototipoIndustrial
     */
    @WebEndpoint(name = "servicePrototipoIndustrialPort")
    public ServicePrototipoIndustrial getServicePrototipoIndustrialPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "servicePrototipoIndustrialPort"), ServicePrototipoIndustrial.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICEPROTOTIPOINDUSTRIALSERVICE_EXCEPTION!= null) {
            throw ISERVICEPROTOTIPOINDUSTRIALSERVICE_EXCEPTION;
        }
        return ISERVICEPROTOTIPOINDUSTRIALSERVICE_WSDL_LOCATION;
    }

}
