
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceCapituloLibroInvestigacionService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://10.8.0.3:8081/flujoCapituloLibroInvestigacion?wsdl")
public class IServiceCapituloLibroInvestigacionService
    extends Service
{

    private final static URL ISERVICECAPITULOLIBROINVESTIGACIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICECAPITULOLIBROINVESTIGACIONSERVICE_EXCEPTION;
    private final static QName ISERVICECAPITULOLIBROINVESTIGACIONSERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceCapituloLibroInvestigacionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.8.0.3:8081/flujoCapituloLibroInvestigacion?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICECAPITULOLIBROINVESTIGACIONSERVICE_WSDL_LOCATION = url;
        ISERVICECAPITULOLIBROINVESTIGACIONSERVICE_EXCEPTION = e;
    }

    public IServiceCapituloLibroInvestigacionService() {
        super(__getWsdlLocation(), ISERVICECAPITULOLIBROINVESTIGACIONSERVICE_QNAME);
    }

    public IServiceCapituloLibroInvestigacionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICECAPITULOLIBROINVESTIGACIONSERVICE_QNAME, features);
    }

    public IServiceCapituloLibroInvestigacionService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICECAPITULOLIBROINVESTIGACIONSERVICE_QNAME);
    }

    public IServiceCapituloLibroInvestigacionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICECAPITULOLIBROINVESTIGACIONSERVICE_QNAME, features);
    }

    public IServiceCapituloLibroInvestigacionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceCapituloLibroInvestigacionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceCapituloLibroInvestigacion
     */
    @WebEndpoint(name = "serviceCapituloLibroInvestigacionPort")
    public ServiceCapituloLibroInvestigacion getServiceCapituloLibroInvestigacionPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceCapituloLibroInvestigacionPort"), ServiceCapituloLibroInvestigacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceCapituloLibroInvestigacion
     */
    @WebEndpoint(name = "serviceCapituloLibroInvestigacionPort")
    public ServiceCapituloLibroInvestigacion getServiceCapituloLibroInvestigacionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceCapituloLibroInvestigacionPort"), ServiceCapituloLibroInvestigacion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICECAPITULOLIBROINVESTIGACIONSERVICE_EXCEPTION!= null) {
            throw ISERVICECAPITULOLIBROINVESTIGACIONSERVICE_EXCEPTION;
        }
        return ISERVICECAPITULOLIBROINVESTIGACIONSERVICE_WSDL_LOCATION;
    }

}
