
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceBoletinService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://192.168.0.14:8081/flujoBoletin?wsdl")
public class IServiceBoletinService
    extends Service
{

    private final static URL ISERVICEBOLETINSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICEBOLETINSERVICE_EXCEPTION;
    private final static QName ISERVICEBOLETINSERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceBoletinService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.14:8081/flujoBoletin?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICEBOLETINSERVICE_WSDL_LOCATION = url;
        ISERVICEBOLETINSERVICE_EXCEPTION = e;
    }

    public IServiceBoletinService() {
        super(__getWsdlLocation(), ISERVICEBOLETINSERVICE_QNAME);
    }

    public IServiceBoletinService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICEBOLETINSERVICE_QNAME, features);
    }

    public IServiceBoletinService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICEBOLETINSERVICE_QNAME);
    }

    public IServiceBoletinService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICEBOLETINSERVICE_QNAME, features);
    }

    public IServiceBoletinService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceBoletinService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceBoletin
     */
    @WebEndpoint(name = "serviceBoletinPort")
    public ServiceBoletin getServiceBoletinPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceBoletinPort"), ServiceBoletin.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceBoletin
     */
    @WebEndpoint(name = "serviceBoletinPort")
    public ServiceBoletin getServiceBoletinPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceBoletinPort"), ServiceBoletin.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICEBOLETINSERVICE_EXCEPTION!= null) {
            throw ISERVICEBOLETINSERVICE_EXCEPTION;
        }
        return ISERVICEBOLETINSERVICE_WSDL_LOCATION;
    }

}
