
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceSoftwareService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://10.8.0.3:8081/flujoSoftware?wsdl")
public class IServiceSoftwareService
    extends Service
{

    private final static URL ISERVICESOFTWARESERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICESOFTWARESERVICE_EXCEPTION;
    private final static QName ISERVICESOFTWARESERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceSoftwareService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.8.0.3:8081/flujoSoftware?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICESOFTWARESERVICE_WSDL_LOCATION = url;
        ISERVICESOFTWARESERVICE_EXCEPTION = e;
    }

    public IServiceSoftwareService() {
        super(__getWsdlLocation(), ISERVICESOFTWARESERVICE_QNAME);
    }

    public IServiceSoftwareService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICESOFTWARESERVICE_QNAME, features);
    }

    public IServiceSoftwareService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICESOFTWARESERVICE_QNAME);
    }

    public IServiceSoftwareService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICESOFTWARESERVICE_QNAME, features);
    }

    public IServiceSoftwareService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceSoftwareService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceSoftware
     */
    @WebEndpoint(name = "serviceSoftwarePort")
    public ServiceSoftware getServiceSoftwarePort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceSoftwarePort"), ServiceSoftware.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSoftware
     */
    @WebEndpoint(name = "serviceSoftwarePort")
    public ServiceSoftware getServiceSoftwarePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceSoftwarePort"), ServiceSoftware.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICESOFTWARESERVICE_EXCEPTION!= null) {
            throw ISERVICESOFTWARESERVICE_EXCEPTION;
        }
        return ISERVICESOFTWARESERVICE_WSDL_LOCATION;
    }

}
