
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceLibroInvestigacionService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://192.168.0.14:8081/flujoLibroInvestigacion?wsdl")
public class IServiceLibroInvestigacionService
    extends Service
{

    private final static URL ISERVICELIBROINVESTIGACIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICELIBROINVESTIGACIONSERVICE_EXCEPTION;
    private final static QName ISERVICELIBROINVESTIGACIONSERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceLibroInvestigacionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.14:8081/flujoLibroInvestigacion?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICELIBROINVESTIGACIONSERVICE_WSDL_LOCATION = url;
        ISERVICELIBROINVESTIGACIONSERVICE_EXCEPTION = e;
    }

    public IServiceLibroInvestigacionService() {
        super(__getWsdlLocation(), ISERVICELIBROINVESTIGACIONSERVICE_QNAME);
    }

    public IServiceLibroInvestigacionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICELIBROINVESTIGACIONSERVICE_QNAME, features);
    }

    public IServiceLibroInvestigacionService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICELIBROINVESTIGACIONSERVICE_QNAME);
    }

    public IServiceLibroInvestigacionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICELIBROINVESTIGACIONSERVICE_QNAME, features);
    }

    public IServiceLibroInvestigacionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceLibroInvestigacionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceLibroInvestigacion
     */
    @WebEndpoint(name = "serviceLibroInvestigacionPort")
    public ServiceLibroInvestigacion getServiceLibroInvestigacionPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceLibroInvestigacionPort"), ServiceLibroInvestigacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceLibroInvestigacion
     */
    @WebEndpoint(name = "serviceLibroInvestigacionPort")
    public ServiceLibroInvestigacion getServiceLibroInvestigacionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceLibroInvestigacionPort"), ServiceLibroInvestigacion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICELIBROINVESTIGACIONSERVICE_EXCEPTION!= null) {
            throw ISERVICELIBROINVESTIGACIONSERVICE_EXCEPTION;
        }
        return ISERVICELIBROINVESTIGACIONSERVICE_WSDL_LOCATION;
    }

}
