
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceDisenoIndustrialService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://10.8.0.3:8081/flujoDisenoIndustrial?wsdl")
public class IServiceDisenoIndustrialService
    extends Service
{

    private final static URL ISERVICEDISENOINDUSTRIALSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICEDISENOINDUSTRIALSERVICE_EXCEPTION;
    private final static QName ISERVICEDISENOINDUSTRIALSERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceDisenoIndustrialService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.8.0.3:8081/flujoDisenoIndustrial?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICEDISENOINDUSTRIALSERVICE_WSDL_LOCATION = url;
        ISERVICEDISENOINDUSTRIALSERVICE_EXCEPTION = e;
    }

    public IServiceDisenoIndustrialService() {
        super(__getWsdlLocation(), ISERVICEDISENOINDUSTRIALSERVICE_QNAME);
    }

    public IServiceDisenoIndustrialService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICEDISENOINDUSTRIALSERVICE_QNAME, features);
    }

    public IServiceDisenoIndustrialService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICEDISENOINDUSTRIALSERVICE_QNAME);
    }

    public IServiceDisenoIndustrialService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICEDISENOINDUSTRIALSERVICE_QNAME, features);
    }

    public IServiceDisenoIndustrialService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceDisenoIndustrialService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceDisenoIndustrial
     */
    @WebEndpoint(name = "serviceDisenoIndustrialPort")
    public ServiceDisenoIndustrial getServiceDisenoIndustrialPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceDisenoIndustrialPort"), ServiceDisenoIndustrial.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceDisenoIndustrial
     */
    @WebEndpoint(name = "serviceDisenoIndustrialPort")
    public ServiceDisenoIndustrial getServiceDisenoIndustrialPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceDisenoIndustrialPort"), ServiceDisenoIndustrial.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICEDISENOINDUSTRIALSERVICE_EXCEPTION!= null) {
            throw ISERVICEDISENOINDUSTRIALSERVICE_EXCEPTION;
        }
        return ISERVICEDISENOINDUSTRIALSERVICE_WSDL_LOCATION;
    }

}
