
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceSecretoEmpresarialService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://192.168.0.14:8081/flujoSecretoEmpresarial?wsdl")
public class IServiceSecretoEmpresarialService
    extends Service
{

    private final static URL ISERVICESECRETOEMPRESARIALSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICESECRETOEMPRESARIALSERVICE_EXCEPTION;
    private final static QName ISERVICESECRETOEMPRESARIALSERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceSecretoEmpresarialService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.14:8081/flujoSecretoEmpresarial?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICESECRETOEMPRESARIALSERVICE_WSDL_LOCATION = url;
        ISERVICESECRETOEMPRESARIALSERVICE_EXCEPTION = e;
    }

    public IServiceSecretoEmpresarialService() {
        super(__getWsdlLocation(), ISERVICESECRETOEMPRESARIALSERVICE_QNAME);
    }

    public IServiceSecretoEmpresarialService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICESECRETOEMPRESARIALSERVICE_QNAME, features);
    }

    public IServiceSecretoEmpresarialService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICESECRETOEMPRESARIALSERVICE_QNAME);
    }

    public IServiceSecretoEmpresarialService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICESECRETOEMPRESARIALSERVICE_QNAME, features);
    }

    public IServiceSecretoEmpresarialService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceSecretoEmpresarialService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceSecretoEmpresarial
     */
    @WebEndpoint(name = "serviceSecretoEmpresarialPort")
    public ServiceSecretoEmpresarial getServiceSecretoEmpresarialPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceSecretoEmpresarialPort"), ServiceSecretoEmpresarial.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSecretoEmpresarial
     */
    @WebEndpoint(name = "serviceSecretoEmpresarialPort")
    public ServiceSecretoEmpresarial getServiceSecretoEmpresarialPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceSecretoEmpresarialPort"), ServiceSecretoEmpresarial.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICESECRETOEMPRESARIALSERVICE_EXCEPTION!= null) {
            throw ISERVICESECRETOEMPRESARIALSERVICE_EXCEPTION;
        }
        return ISERVICESECRETOEMPRESARIALSERVICE_WSDL_LOCATION;
    }

}
