
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceEdicionService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://10.8.0.4:8081/flujoEdicion?wsdl")
public class IServiceEdicionService
    extends Service
{

    private final static URL ISERVICEEDICIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICEEDICIONSERVICE_EXCEPTION;
    private final static QName ISERVICEEDICIONSERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceEdicionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.8.0.4:8081/flujoEdicion?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICEEDICIONSERVICE_WSDL_LOCATION = url;
        ISERVICEEDICIONSERVICE_EXCEPTION = e;
    }

    public IServiceEdicionService() {
        super(__getWsdlLocation(), ISERVICEEDICIONSERVICE_QNAME);
    }

    public IServiceEdicionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICEEDICIONSERVICE_QNAME, features);
    }

    public IServiceEdicionService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICEEDICIONSERVICE_QNAME);
    }

    public IServiceEdicionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICEEDICIONSERVICE_QNAME, features);
    }

    public IServiceEdicionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceEdicionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceEdicion
     */
    @WebEndpoint(name = "serviceEdicionPort")
    public ServiceEdicion getServiceEdicionPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceEdicionPort"), ServiceEdicion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceEdicion
     */
    @WebEndpoint(name = "serviceEdicionPort")
    public ServiceEdicion getServiceEdicionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceEdicionPort"), ServiceEdicion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICEEDICIONSERVICE_EXCEPTION!= null) {
            throw ISERVICEEDICIONSERVICE_EXCEPTION;
        }
        return ISERVICEEDICIONSERVICE_WSDL_LOCATION;
    }

}
