
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceInformeFinalInvestigacionService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://192.168.0.14:8081/flujoInformeFinalInvestigacion?wsdl")
public class IServiceInformeFinalInvestigacionService
    extends Service
{

    private final static URL ISERVICEINFORMEFINALINVESTIGACIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICEINFORMEFINALINVESTIGACIONSERVICE_EXCEPTION;
    private final static QName ISERVICEINFORMEFINALINVESTIGACIONSERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceInformeFinalInvestigacionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.14:8081/flujoInformeFinalInvestigacion?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICEINFORMEFINALINVESTIGACIONSERVICE_WSDL_LOCATION = url;
        ISERVICEINFORMEFINALINVESTIGACIONSERVICE_EXCEPTION = e;
    }

    public IServiceInformeFinalInvestigacionService() {
        super(__getWsdlLocation(), ISERVICEINFORMEFINALINVESTIGACIONSERVICE_QNAME);
    }

    public IServiceInformeFinalInvestigacionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICEINFORMEFINALINVESTIGACIONSERVICE_QNAME, features);
    }

    public IServiceInformeFinalInvestigacionService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICEINFORMEFINALINVESTIGACIONSERVICE_QNAME);
    }

    public IServiceInformeFinalInvestigacionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICEINFORMEFINALINVESTIGACIONSERVICE_QNAME, features);
    }

    public IServiceInformeFinalInvestigacionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceInformeFinalInvestigacionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceInformeFinalInvestigacion
     */
    @WebEndpoint(name = "serviceInformeFinalInvestigacionPort")
    public ServiceInformeFinalInvestigacion getServiceInformeFinalInvestigacionPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceInformeFinalInvestigacionPort"), ServiceInformeFinalInvestigacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceInformeFinalInvestigacion
     */
    @WebEndpoint(name = "serviceInformeFinalInvestigacionPort")
    public ServiceInformeFinalInvestigacion getServiceInformeFinalInvestigacionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceInformeFinalInvestigacionPort"), ServiceInformeFinalInvestigacion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICEINFORMEFINALINVESTIGACIONSERVICE_EXCEPTION!= null) {
            throw ISERVICEINFORMEFINALINVESTIGACIONSERVICE_EXCEPTION;
        }
        return ISERVICEINFORMEFINALINVESTIGACIONSERVICE_WSDL_LOCATION;
    }

}
