
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceTrabajoGradoService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://10.8.0.3:8081/flujoTrabajoGrado?wsdl")
public class IServiceTrabajoGradoService
    extends Service
{

    private final static URL ISERVICETRABAJOGRADOSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICETRABAJOGRADOSERVICE_EXCEPTION;
    private final static QName ISERVICETRABAJOGRADOSERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceTrabajoGradoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.8.0.3:8081/flujoTrabajoGrado?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICETRABAJOGRADOSERVICE_WSDL_LOCATION = url;
        ISERVICETRABAJOGRADOSERVICE_EXCEPTION = e;
    }

    public IServiceTrabajoGradoService() {
        super(__getWsdlLocation(), ISERVICETRABAJOGRADOSERVICE_QNAME);
    }

    public IServiceTrabajoGradoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICETRABAJOGRADOSERVICE_QNAME, features);
    }

    public IServiceTrabajoGradoService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICETRABAJOGRADOSERVICE_QNAME);
    }

    public IServiceTrabajoGradoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICETRABAJOGRADOSERVICE_QNAME, features);
    }

    public IServiceTrabajoGradoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceTrabajoGradoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceTrabajoGrado
     */
    @WebEndpoint(name = "serviceTrabajoGradoPort")
    public ServiceTrabajoGrado getServiceTrabajoGradoPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceTrabajoGradoPort"), ServiceTrabajoGrado.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceTrabajoGrado
     */
    @WebEndpoint(name = "serviceTrabajoGradoPort")
    public ServiceTrabajoGrado getServiceTrabajoGradoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceTrabajoGradoPort"), ServiceTrabajoGrado.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICETRABAJOGRADOSERVICE_EXCEPTION!= null) {
            throw ISERVICETRABAJOGRADOSERVICE_EXCEPTION;
        }
        return ISERVICETRABAJOGRADOSERVICE_WSDL_LOCATION;
    }

}
