
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceEstrategiaComunicacionConocimientoService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://10.8.0.3:8081/flujoEstrategiaComunicacionConocimiento?wsdl")
public class IServiceEstrategiaComunicacionConocimientoService
    extends Service
{

    private final static URL ISERVICEESTRATEGIACOMUNICACIONCONOCIMIENTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICEESTRATEGIACOMUNICACIONCONOCIMIENTOSERVICE_EXCEPTION;
    private final static QName ISERVICEESTRATEGIACOMUNICACIONCONOCIMIENTOSERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceEstrategiaComunicacionConocimientoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.8.0.3:8081/flujoEstrategiaComunicacionConocimiento?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICEESTRATEGIACOMUNICACIONCONOCIMIENTOSERVICE_WSDL_LOCATION = url;
        ISERVICEESTRATEGIACOMUNICACIONCONOCIMIENTOSERVICE_EXCEPTION = e;
    }

    public IServiceEstrategiaComunicacionConocimientoService() {
        super(__getWsdlLocation(), ISERVICEESTRATEGIACOMUNICACIONCONOCIMIENTOSERVICE_QNAME);
    }

    public IServiceEstrategiaComunicacionConocimientoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICEESTRATEGIACOMUNICACIONCONOCIMIENTOSERVICE_QNAME, features);
    }

    public IServiceEstrategiaComunicacionConocimientoService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICEESTRATEGIACOMUNICACIONCONOCIMIENTOSERVICE_QNAME);
    }

    public IServiceEstrategiaComunicacionConocimientoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICEESTRATEGIACOMUNICACIONCONOCIMIENTOSERVICE_QNAME, features);
    }

    public IServiceEstrategiaComunicacionConocimientoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceEstrategiaComunicacionConocimientoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceEstrategiaComunicacionConocimiento
     */
    @WebEndpoint(name = "serviceEstrategiaComunicacionConocimientoPort")
    public ServiceEstrategiaComunicacionConocimiento getServiceEstrategiaComunicacionConocimientoPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceEstrategiaComunicacionConocimientoPort"), ServiceEstrategiaComunicacionConocimiento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceEstrategiaComunicacionConocimiento
     */
    @WebEndpoint(name = "serviceEstrategiaComunicacionConocimientoPort")
    public ServiceEstrategiaComunicacionConocimiento getServiceEstrategiaComunicacionConocimientoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceEstrategiaComunicacionConocimientoPort"), ServiceEstrategiaComunicacionConocimiento.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICEESTRATEGIACOMUNICACIONCONOCIMIENTOSERVICE_EXCEPTION!= null) {
            throw ISERVICEESTRATEGIACOMUNICACIONCONOCIMIENTOSERVICE_EXCEPTION;
        }
        return ISERVICEESTRATEGIACOMUNICACIONCONOCIMIENTOSERVICE_WSDL_LOCATION;
    }

}
