
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceProyectoExtensionCTIService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://10.8.0.4:8081/flujoProyectoExtensionCTI?wsdl")
public class IServiceProyectoExtensionCTIService
    extends Service
{

    private final static URL ISERVICEPROYECTOEXTENSIONCTISERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICEPROYECTOEXTENSIONCTISERVICE_EXCEPTION;
    private final static QName ISERVICEPROYECTOEXTENSIONCTISERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceProyectoExtensionCTIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.8.0.4:8081/flujoProyectoExtensionCTI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICEPROYECTOEXTENSIONCTISERVICE_WSDL_LOCATION = url;
        ISERVICEPROYECTOEXTENSIONCTISERVICE_EXCEPTION = e;
    }

    public IServiceProyectoExtensionCTIService() {
        super(__getWsdlLocation(), ISERVICEPROYECTOEXTENSIONCTISERVICE_QNAME);
    }

    public IServiceProyectoExtensionCTIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICEPROYECTOEXTENSIONCTISERVICE_QNAME, features);
    }

    public IServiceProyectoExtensionCTIService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICEPROYECTOEXTENSIONCTISERVICE_QNAME);
    }

    public IServiceProyectoExtensionCTIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICEPROYECTOEXTENSIONCTISERVICE_QNAME, features);
    }

    public IServiceProyectoExtensionCTIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceProyectoExtensionCTIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceProyectoExtensionCTI
     */
    @WebEndpoint(name = "serviceProyectoExtensionCTIPort")
    public ServiceProyectoExtensionCTI getServiceProyectoExtensionCTIPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceProyectoExtensionCTIPort"), ServiceProyectoExtensionCTI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceProyectoExtensionCTI
     */
    @WebEndpoint(name = "serviceProyectoExtensionCTIPort")
    public ServiceProyectoExtensionCTI getServiceProyectoExtensionCTIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceProyectoExtensionCTIPort"), ServiceProyectoExtensionCTI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICEPROYECTOEXTENSIONCTISERVICE_EXCEPTION!= null) {
            throw ISERVICEPROYECTOEXTENSIONCTISERVICE_EXCEPTION;
        }
        return ISERVICEPROYECTOEXTENSIONCTISERVICE_WSDL_LOCATION;
    }

}
