
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceArticuloInvestigacionService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://10.8.0.4:8081/flujoArticuloInvestigacion?wsdl")
public class IServiceArticuloInvestigacionService
    extends Service
{

    private final static URL ISERVICEARTICULOINVESTIGACIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICEARTICULOINVESTIGACIONSERVICE_EXCEPTION;
    private final static QName ISERVICEARTICULOINVESTIGACIONSERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceArticuloInvestigacionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.8.0.4:8081/flujoArticuloInvestigacion?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICEARTICULOINVESTIGACIONSERVICE_WSDL_LOCATION = url;
        ISERVICEARTICULOINVESTIGACIONSERVICE_EXCEPTION = e;
    }

    public IServiceArticuloInvestigacionService() {
        super(__getWsdlLocation(), ISERVICEARTICULOINVESTIGACIONSERVICE_QNAME);
    }

    public IServiceArticuloInvestigacionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICEARTICULOINVESTIGACIONSERVICE_QNAME, features);
    }

    public IServiceArticuloInvestigacionService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICEARTICULOINVESTIGACIONSERVICE_QNAME);
    }

    public IServiceArticuloInvestigacionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICEARTICULOINVESTIGACIONSERVICE_QNAME, features);
    }

    public IServiceArticuloInvestigacionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceArticuloInvestigacionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceArticuloInvestigacion
     */
    @WebEndpoint(name = "serviceArticuloInvestigacionPort")
    public ServiceArticuloInvestigacion getServiceArticuloInvestigacionPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceArticuloInvestigacionPort"), ServiceArticuloInvestigacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceArticuloInvestigacion
     */
    @WebEndpoint(name = "serviceArticuloInvestigacionPort")
    public ServiceArticuloInvestigacion getServiceArticuloInvestigacionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceArticuloInvestigacionPort"), ServiceArticuloInvestigacion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICEARTICULOINVESTIGACIONSERVICE_EXCEPTION!= null) {
            throw ISERVICEARTICULOINVESTIGACIONSERVICE_EXCEPTION;
        }
        return ISERVICEARTICULOINVESTIGACIONSERVICE_WSDL_LOCATION;
    }

}
