
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceInformeTecnicoFinalService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://192.168.0.14:8081/flujoInformeTecnicoFinal?wsdl")
public class IServiceInformeTecnicoFinalService
    extends Service
{

    private final static URL ISERVICEINFORMETECNICOFINALSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICEINFORMETECNICOFINALSERVICE_EXCEPTION;
    private final static QName ISERVICEINFORMETECNICOFINALSERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceInformeTecnicoFinalService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.14:8081/flujoInformeTecnicoFinal?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICEINFORMETECNICOFINALSERVICE_WSDL_LOCATION = url;
        ISERVICEINFORMETECNICOFINALSERVICE_EXCEPTION = e;
    }

    public IServiceInformeTecnicoFinalService() {
        super(__getWsdlLocation(), ISERVICEINFORMETECNICOFINALSERVICE_QNAME);
    }

    public IServiceInformeTecnicoFinalService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICEINFORMETECNICOFINALSERVICE_QNAME, features);
    }

    public IServiceInformeTecnicoFinalService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICEINFORMETECNICOFINALSERVICE_QNAME);
    }

    public IServiceInformeTecnicoFinalService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICEINFORMETECNICOFINALSERVICE_QNAME, features);
    }

    public IServiceInformeTecnicoFinalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceInformeTecnicoFinalService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceInformeTecnicoFinal
     */
    @WebEndpoint(name = "serviceInformeTecnicoFinalPort")
    public ServiceInformeTecnicoFinal getServiceInformeTecnicoFinalPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceInformeTecnicoFinalPort"), ServiceInformeTecnicoFinal.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceInformeTecnicoFinal
     */
    @WebEndpoint(name = "serviceInformeTecnicoFinalPort")
    public ServiceInformeTecnicoFinal getServiceInformeTecnicoFinalPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceInformeTecnicoFinalPort"), ServiceInformeTecnicoFinal.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICEINFORMETECNICOFINALSERVICE_EXCEPTION!= null) {
            throw ISERVICEINFORMETECNICOFINALSERVICE_EXCEPTION;
        }
        return ISERVICEINFORMETECNICOFINALSERVICE_WSDL_LOCATION;
    }

}
