
package co.com.ic2.colciencias.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceEstrategiaPedagogicaFomentoCTIService", targetNamespace = "http://ws.colciencias.ic2.com.co/", wsdlLocation = "http://10.8.0.4:8081/flujoEstrategiaPedagogicaFomentoCTI?wsdl")
public class IServiceEstrategiaPedagogicaFomentoCTIService
    extends Service
{

    private final static URL ISERVICEESTRATEGIAPEDAGOGICAFOMENTOCTISERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICEESTRATEGIAPEDAGOGICAFOMENTOCTISERVICE_EXCEPTION;
    private final static QName ISERVICEESTRATEGIAPEDAGOGICAFOMENTOCTISERVICE_QNAME = new QName("http://ws.colciencias.ic2.com.co/", "IServiceEstrategiaPedagogicaFomentoCTIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.8.0.4:8081/flujoEstrategiaPedagogicaFomentoCTI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICEESTRATEGIAPEDAGOGICAFOMENTOCTISERVICE_WSDL_LOCATION = url;
        ISERVICEESTRATEGIAPEDAGOGICAFOMENTOCTISERVICE_EXCEPTION = e;
    }

    public IServiceEstrategiaPedagogicaFomentoCTIService() {
        super(__getWsdlLocation(), ISERVICEESTRATEGIAPEDAGOGICAFOMENTOCTISERVICE_QNAME);
    }

    public IServiceEstrategiaPedagogicaFomentoCTIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICEESTRATEGIAPEDAGOGICAFOMENTOCTISERVICE_QNAME, features);
    }

    public IServiceEstrategiaPedagogicaFomentoCTIService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICEESTRATEGIAPEDAGOGICAFOMENTOCTISERVICE_QNAME);
    }

    public IServiceEstrategiaPedagogicaFomentoCTIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICEESTRATEGIAPEDAGOGICAFOMENTOCTISERVICE_QNAME, features);
    }

    public IServiceEstrategiaPedagogicaFomentoCTIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceEstrategiaPedagogicaFomentoCTIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceEstrategiaPedagogicaFomentoCTI
     */
    @WebEndpoint(name = "serviceEstrategiaPedagogicaFomentoCTIPort")
    public ServiceEstrategiaPedagogicaFomentoCTI getServiceEstrategiaPedagogicaFomentoCTIPort() {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceEstrategiaPedagogicaFomentoCTIPort"), ServiceEstrategiaPedagogicaFomentoCTI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceEstrategiaPedagogicaFomentoCTI
     */
    @WebEndpoint(name = "serviceEstrategiaPedagogicaFomentoCTIPort")
    public ServiceEstrategiaPedagogicaFomentoCTI getServiceEstrategiaPedagogicaFomentoCTIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.colciencias.ic2.com.co/", "serviceEstrategiaPedagogicaFomentoCTIPort"), ServiceEstrategiaPedagogicaFomentoCTI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICEESTRATEGIAPEDAGOGICAFOMENTOCTISERVICE_EXCEPTION!= null) {
            throw ISERVICEESTRATEGIAPEDAGOGICAFOMENTOCTISERVICE_EXCEPTION;
        }
        return ISERVICEESTRATEGIAPEDAGOGICAFOMENTOCTISERVICE_WSDL_LOCATION;
    }

}
