
package co.com.ic2.colciencias.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.GrupoInvestigacion;
import co.com.ic2.colciencias.service.scraper.ExtraerGrupoInvestigacionResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceScraperColciencias", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.ObjectFactory.class,
    co.com.ic2.colciencias.service.scraper.ObjectFactory.class,
    co.com.ic2.colciencias.ws.ObjectFactory.class
})
public interface ServiceScraperColciencias {


    /**
     * 
     * @param integrantesDetalles
     * @param urlGruplac
     * @param anoFinVentanaObservacion
     * @param integrantes
     * @param productos
     * @return
     *     returns co.com.ic2.colciencias.gruplac.GrupoInvestigacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "extraerGrupoInvestigacionPublico", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ExtraerGrupoInvestigacionPublico")
    @ResponseWrapper(localName = "extraerGrupoInvestigacionPublicoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ExtraerGrupoInvestigacionPublicoResponse")
    public GrupoInvestigacion extraerGrupoInvestigacionPublico(
        @WebParam(name = "urlGruplac", targetNamespace = "")
        String urlGruplac,
        @WebParam(name = "integrantes", targetNamespace = "")
        boolean integrantes,
        @WebParam(name = "integrantesDetalles", targetNamespace = "")
        boolean integrantesDetalles,
        @WebParam(name = "productos", targetNamespace = "")
        boolean productos,
        @WebParam(name = "anoFinVentanaObservacion", targetNamespace = "")
        int anoFinVentanaObservacion);

    /**
     * 
     * @param anoFinVentanaObservacion
     * @param identificacion
     * @param contrasena
     * @param paisNacimiento
     * @param tipoNacionalidad
     * @param nombre
     * @param idGrupo
     * @return
     *     returns co.com.ic2.colciencias.service.scraper.ExtraerGrupoInvestigacionResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "extraerGrupoInvestigacion", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ExtraerGrupoInvestigacion")
    @ResponseWrapper(localName = "extraerGrupoInvestigacionResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ExtraerGrupoInvestigacionResponse")
    public ExtraerGrupoInvestigacionResponse extraerGrupoInvestigacion(
        @WebParam(name = "tipoNacionalidad", targetNamespace = "")
        String tipoNacionalidad,
        @WebParam(name = "paisNacimiento", targetNamespace = "")
        String paisNacimiento,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "identificacion", targetNamespace = "")
        String identificacion,
        @WebParam(name = "contrasena", targetNamespace = "")
        String contrasena,
        @WebParam(name = "idGrupo", targetNamespace = "")
        int idGrupo,
        @WebParam(name = "anoFinVentanaObservacion", targetNamespace = "")
        int anoFinVentanaObservacion);

}
