
package co.com.ic2.colciencias.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.productosinvestigacion.SignoDistintivo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceSignoDistintivo", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.ws.ObjectFactory.class
})
public interface ServiceSignoDistintivo {


    /**
     * 
     * @param codigo
     * @param ano
     * @param certificadoRegistro
     * @param categoria
     * @param condicionesUso
     * @param titulo
     * @param mes
     * @param numeroRegistro
     * @param paisObtencion
     * @param clasificado
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarSignoDistintivo", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarSignoDistintivo")
    @ResponseWrapper(localName = "insertarSignoDistintivoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarSignoDistintivoResponse")
    public String insertarSignoDistintivo(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "numeroRegistro", targetNamespace = "")
        String numeroRegistro,
        @WebParam(name = "titulo", targetNamespace = "")
        String titulo,
        @WebParam(name = "ano", targetNamespace = "")
        int ano,
        @WebParam(name = "mes", targetNamespace = "")
        int mes,
        @WebParam(name = "certificadoRegistro", targetNamespace = "")
        boolean certificadoRegistro,
        @WebParam(name = "condicionesUso", targetNamespace = "")
        String condicionesUso,
        @WebParam(name = "paisObtencion", targetNamespace = "")
        int paisObtencion,
        @WebParam(name = "categoria", targetNamespace = "")
        String categoria,
        @WebParam(name = "clasificado", targetNamespace = "")
        boolean clasificado);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.SignoDistintivo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarSignosDistintivosGrupo", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarSignosDistintivosGrupo")
    @ResponseWrapper(localName = "consultarSignosDistintivosGrupoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarSignosDistintivosGrupoResponse")
    public List<SignoDistintivo> consultarSignosDistintivosGrupo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.SignoDistintivo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarSignosDistintivos", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarSignosDistintivos")
    @ResponseWrapper(localName = "consultarSignosDistintivosResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarSignosDistintivosResponse")
    public List<SignoDistintivo> consultarSignosDistintivos();

    /**
     * 
     * @param codigoGrupo
     * @param signosDistintivos
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarSignoDistintivos", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarSignoDistintivos")
    @ResponseWrapper(localName = "insertarSignoDistintivosResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarSignoDistintivosResponse")
    public String insertarSignoDistintivos(
        @WebParam(name = "codigoGrupo", targetNamespace = "")
        String codigoGrupo,
        @WebParam(name = "signosDistintivos", targetNamespace = "")
        List<SignoDistintivo> signosDistintivos);

}
