
package co.com.ic2.colciencias.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceRedNeuronal", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceRedNeuronal {


    /**
     * 
     * @param estadoActual
     * @param categoriaObjetivo
     * @param categoriaActual
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ejecutarRecomendacion", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.EjecutarRecomendacion")
    @ResponseWrapper(localName = "ejecutarRecomendacionResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.EjecutarRecomendacionResponse")
    public String ejecutarRecomendacion(
        @WebParam(name = "estadoActual", targetNamespace = "")
        String estadoActual,
        @WebParam(name = "categoriaActual", targetNamespace = "")
        String categoriaActual,
        @WebParam(name = "categoriaObjetivo", targetNamespace = "")
        String categoriaObjetivo);

}
