
package co.com.ic2.colciencias.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.productosinvestigacion.ParticipacionCiudadanaProyectoCTI;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceParticipacionCiudadanaProyectoCTI", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.ObjectFactory.class,
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.ws.ObjectFactory.class
})
public interface ServiceParticipacionCiudadanaProyectoCTI {


    /**
     * 
     * @param codigoGrupo
     * @param participacionesCti
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarParticipacionesCiudadanasProyectosCTI", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarParticipacionesCiudadanasProyectosCTI")
    @ResponseWrapper(localName = "insertarParticipacionesCiudadanasProyectosCTIResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarParticipacionesCiudadanasProyectosCTIResponse")
    public String insertarParticipacionesCiudadanasProyectosCTI(
        @WebParam(name = "codigoGrupo", targetNamespace = "")
        String codigoGrupo,
        @WebParam(name = "participacionesCti", targetNamespace = "")
        List<ParticipacionCiudadanaProyectoCTI> participacionesCti);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.ParticipacionCiudadanaProyectoCTI>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarParticipacionesCiudadanasProyectosCTIGrupo", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarParticipacionesCiudadanasProyectosCTIGrupo")
    @ResponseWrapper(localName = "consultarParticipacionesCiudadanasProyectosCTIGrupoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarParticipacionesCiudadanasProyectosCTIGrupoResponse")
    public List<ParticipacionCiudadanaProyectoCTI> consultarParticipacionesCiudadanasProyectosCTIGrupo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param codigoGrupoInvestigacion
     * @param codigo
     * @param fechaInicio
     * @param categoria
     * @param nombreComunidad
     * @param titulo
     * @param investigadorPrincipal
     * @param constanciaParticipacion
     * @param clasificado
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarParticipacionCiudadanaProyectoCTI", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarParticipacionCiudadanaProyectoCTI")
    @ResponseWrapper(localName = "insertarParticipacionCiudadanaProyectoCTIResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarParticipacionCiudadanaProyectoCTIResponse")
    public String insertarParticipacionCiudadanaProyectoCTI(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "titulo", targetNamespace = "")
        String titulo,
        @WebParam(name = "fechaInicio", targetNamespace = "")
        String fechaInicio,
        @WebParam(name = "nombreComunidad", targetNamespace = "")
        String nombreComunidad,
        @WebParam(name = "investigadorPrincipal", targetNamespace = "")
        String investigadorPrincipal,
        @WebParam(name = "constanciaParticipacion", targetNamespace = "")
        boolean constanciaParticipacion,
        @WebParam(name = "categoria", targetNamespace = "")
        String categoria,
        @WebParam(name = "clasificado", targetNamespace = "")
        boolean clasificado,
        @WebParam(name = "codigoGrupoInvestigacion", targetNamespace = "")
        boolean codigoGrupoInvestigacion);

    /**
     * 
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.ParticipacionCiudadanaProyectoCTI>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarParticipacionesCiudadanasProyectosCTI", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarParticipacionesCiudadanasProyectosCTI")
    @ResponseWrapper(localName = "consultarParticipacionesCiudadanasProyectosCTIResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarParticipacionesCiudadanasProyectosCTIResponse")
    public List<ParticipacionCiudadanaProyectoCTI> consultarParticipacionesCiudadanasProyectosCTI();

}
