
package co.com.ic2.colciencias.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.productosinvestigacion.ArticuloInvestigacion;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceArticuloInvestigacion", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.ObjectFactory.class,
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.ws.ObjectFactory.class
})
public interface ServiceArticuloInvestigacion {


    /**
     * 
     * @param articulos
     * @param codigoGrupo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarArticulosInvestigacion", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarArticulosInvestigacion")
    @ResponseWrapper(localName = "insertarArticulosInvestigacionResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarArticulosInvestigacionResponse")
    public String insertarArticulosInvestigacion(
        @WebParam(name = "codigoGrupo", targetNamespace = "")
        String codigoGrupo,
        @WebParam(name = "articulos", targetNamespace = "")
        List<ArticuloInvestigacion> articulos);

    /**
     * 
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.ArticuloInvestigacion>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarArticulosInvestigacion", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarArticulosInvestigacion")
    @ResponseWrapper(localName = "consultarArticulosInvestigacionResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarArticulosInvestigacionResponse")
    public List<ArticuloInvestigacion> consultarArticulosInvestigacion();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarClasificacionArticulosInvestigacion", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarClasificacionArticulosInvestigacion")
    @ResponseWrapper(localName = "consultarClasificacionArticulosInvestigacionResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarClasificacionArticulosInvestigacionResponse")
    public String consultarClasificacionArticulosInvestigacion(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.ArticuloInvestigacion>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarArticulosInvestigacionGrupo", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarArticulosInvestigacionGrupo")
    @ResponseWrapper(localName = "consultarArticulosInvestigacionGrupoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarArticulosInvestigacionGrupoResponse")
    public List<ArticuloInvestigacion> consultarArticulosInvestigacionGrupo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param codigo
     * @param paginaWeb
     * @param ano
     * @param volumen
     * @param issnRevista
     * @param categoria
     * @param titulo
     * @param clasificado
     * @param paisPublicacion
     * @param paginaFinal
     * @param mes
     * @param paginaInicial
     * @param doi
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarArticuloInvestigacion", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarArticuloInvestigacion")
    @ResponseWrapper(localName = "insertarArticuloInvestigacionResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarArticuloInvestigacionResponse")
    public String insertarArticuloInvestigacion(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "titulo", targetNamespace = "")
        String titulo,
        @WebParam(name = "ano", targetNamespace = "")
        int ano,
        @WebParam(name = "mes", targetNamespace = "")
        int mes,
        @WebParam(name = "volumen", targetNamespace = "")
        int volumen,
        @WebParam(name = "paginaInicial", targetNamespace = "")
        int paginaInicial,
        @WebParam(name = "paginaFinal", targetNamespace = "")
        int paginaFinal,
        @WebParam(name = "issnRevista", targetNamespace = "")
        int issnRevista,
        @WebParam(name = "paginaWeb", targetNamespace = "")
        String paginaWeb,
        @WebParam(name = "doi", targetNamespace = "")
        String doi,
        @WebParam(name = "paisPublicacion", targetNamespace = "")
        String paisPublicacion,
        @WebParam(name = "categoria", targetNamespace = "")
        String categoria,
        @WebParam(name = "clasificado", targetNamespace = "")
        boolean clasificado);

}
