
package co.com.ic2.colciencias.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.productosinvestigacion.DisenoIndustrial;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceDisenoIndustrial", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.ObjectFactory.class,
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.ws.ObjectFactory.class
})
public interface ServiceDisenoIndustrial {


    /**
     * 
     * @param codigoGrupo
     * @param disenosIndustriales
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarDisenosIndustriales", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarDisenosIndustriales")
    @ResponseWrapper(localName = "insertarDisenosIndustrialesResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarDisenosIndustrialesResponse")
    public String insertarDisenosIndustriales(
        @WebParam(name = "codigoGrupo", targetNamespace = "")
        String codigoGrupo,
        @WebParam(name = "disenosIndustriales", targetNamespace = "")
        List<DisenoIndustrial> disenosIndustriales);

    /**
     * 
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.DisenoIndustrial>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDisenosIndustriales", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarDisenosIndustriales")
    @ResponseWrapper(localName = "consultarDisenosIndustrialesResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarDisenosIndustrialesResponse")
    public List<DisenoIndustrial> consultarDisenosIndustriales();

    /**
     * 
     * @param gaceta
     * @param codigo
     * @param ano
     * @param categoria
     * @param contrato
     * @param numeroRegistro
     * @param tituloRegistro
     * @param paisObtencion
     * @param clasificado
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarDisenoIndustrial", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarDisenoIndustrial")
    @ResponseWrapper(localName = "insertarDisenoIndustrialResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarDisenoIndustrialResponse")
    public String insertarDisenoIndustrial(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "numeroRegistro", targetNamespace = "")
        String numeroRegistro,
        @WebParam(name = "tituloRegistro", targetNamespace = "")
        int tituloRegistro,
        @WebParam(name = "ano", targetNamespace = "")
        int ano,
        @WebParam(name = "gaceta", targetNamespace = "")
        int gaceta,
        @WebParam(name = "paisObtencion", targetNamespace = "")
        int paisObtencion,
        @WebParam(name = "contrato", targetNamespace = "")
        int contrato,
        @WebParam(name = "categoria", targetNamespace = "")
        String categoria,
        @WebParam(name = "clasificado", targetNamespace = "")
        boolean clasificado);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.DisenoIndustrial>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDisenosIndustrialesGrupo", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarDisenosIndustrialesGrupo")
    @ResponseWrapper(localName = "consultarDisenosIndustrialesGrupoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarDisenosIndustrialesGrupoResponse")
    public List<DisenoIndustrial> consultarDisenosIndustrialesGrupo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
