
package co.com.ic2.colciencias.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceSecretoEmpresarial", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSecretoEmpresarial {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarSecretosEmpresriales", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarSecretosEmpresriales")
    @ResponseWrapper(localName = "consultarSecretosEmpresrialesResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarSecretosEmpresrialesResponse")
    public String consultarSecretosEmpresriales();

    /**
     * 
     * @param valorContrato
     * @param codigo
     * @param numeroContrato
     * @param certificacion
     * @param categoria
     * @param nombre
     * @param clasificado
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarSecretoEmpresarial", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarSecretoEmpresarial")
    @ResponseWrapper(localName = "insertarSecretoEmpresarialResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarSecretoEmpresarialResponse")
    public String insertarSecretoEmpresarial(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "valorContrato", targetNamespace = "")
        String valorContrato,
        @WebParam(name = "certificacion", targetNamespace = "")
        boolean certificacion,
        @WebParam(name = "numeroContrato", targetNamespace = "")
        String numeroContrato,
        @WebParam(name = "categoria", targetNamespace = "")
        String categoria,
        @WebParam(name = "clasificado", targetNamespace = "")
        boolean clasificado);

}
