
package co.com.ic2.colciencias.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.productosinvestigacion.PrototipoIndustrial;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "servicePrototipoIndustrial", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.ObjectFactory.class,
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.ws.ObjectFactory.class
})
public interface ServicePrototipoIndustrial {


    /**
     * 
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.PrototipoIndustrial>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarPrototiposIndustriales", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarPrototiposIndustriales")
    @ResponseWrapper(localName = "consultarPrototiposIndustrialesResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarPrototiposIndustrialesResponse")
    public List<PrototipoIndustrial> consultarPrototiposIndustriales();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.PrototipoIndustrial>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarPrototiposIndustrialesGrupo", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarPrototiposIndustrialesGrupo")
    @ResponseWrapper(localName = "consultarPrototiposIndustrialesGrupoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarPrototiposIndustrialesGrupoResponse")
    public List<PrototipoIndustrial> consultarPrototiposIndustrialesGrupo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.lang.Object
     * @throws CloneNotSupportedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "clone", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.Clone")
    @ResponseWrapper(localName = "cloneResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.CloneResponse")
    public Object clone()
        throws CloneNotSupportedException_Exception
    ;

    /**
     * 
     * @param prototiposIndustriales
     * @param codigoGrupo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarPrototiposIndustriales", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarPrototiposIndustriales")
    @ResponseWrapper(localName = "insertarPrototiposIndustrialesResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarPrototiposIndustrialesResponse")
    public String insertarPrototiposIndustriales(
        @WebParam(name = "codigoGrupo", targetNamespace = "")
        String codigoGrupo,
        @WebParam(name = "prototiposIndustriales", targetNamespace = "")
        List<PrototipoIndustrial> prototiposIndustriales);

    /**
     * 
     * @param fecha
     * @param codigo
     * @param institucionFinanciadora
     * @param categoria
     * @param paisObtencion
     * @param nombre
     * @param clasificado
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarPrototipoIndustrial", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarPrototipoIndustrial")
    @ResponseWrapper(localName = "insertarPrototipoIndustrialResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarPrototipoIndustrialResponse")
    public String insertarPrototipoIndustrial(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "fecha", targetNamespace = "")
        String fecha,
        @WebParam(name = "institucionFinanciadora", targetNamespace = "")
        String institucionFinanciadora,
        @WebParam(name = "paisObtencion", targetNamespace = "")
        int paisObtencion,
        @WebParam(name = "categoria", targetNamespace = "")
        String categoria,
        @WebParam(name = "clasificado", targetNamespace = "")
        boolean clasificado);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarClasificacionPrototiposIndustriales", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarClasificacionPrototiposIndustriales")
    @ResponseWrapper(localName = "consultarClasificacionPrototiposIndustrialesResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarClasificacionPrototiposIndustrialesResponse")
    public String consultarClasificacionPrototiposIndustriales(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
