
package co.com.ic2.colciencias.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.GrupoInvestigacion;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceGrupoInvestigacion", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.ObjectFactory.class,
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.ws.ObjectFactory.class
})
public interface ServiceGrupoInvestigacion {


    /**
     * 
     * @param nombre
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarGrupoInvestigacion", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarGrupoInvestigacion")
    @ResponseWrapper(localName = "insertarGrupoInvestigacionResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarGrupoInvestigacionResponse")
    public int insertarGrupoInvestigacion(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre);

    /**
     * 
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.GrupoInvestigacion>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarGruposInvestigacion", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarGruposInvestigacion")
    @ResponseWrapper(localName = "consultarGruposInvestigacionResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarGruposInvestigacionResponse")
    public List<GrupoInvestigacion> consultarGruposInvestigacion();

    /**
     * 
     * @param codigo
     * @return
     *     returns co.com.ic2.colciencias.gruplac.GrupoInvestigacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarGrupoInvestigacion", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarGrupoInvestigacion")
    @ResponseWrapper(localName = "consultarGrupoInvestigacionResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarGrupoInvestigacionResponse")
    public GrupoInvestigacion consultarGrupoInvestigacion(
        @WebParam(name = "codigo", targetNamespace = "")
        int codigo);

}
