
package co.com.ic2.colciencias.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.productosinvestigacion.EstrategiaComunicacionConocimiento;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceEstrategiaComunicacionConocimiento", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.ws.ObjectFactory.class
})
public interface ServiceEstrategiaComunicacionConocimiento {


    /**
     * 
     * @param codigo
     * @param fechaInicio
     * @param certificacion
     * @param lider
     * @param categoria
     * @param nombreComunidad
     * @param nombre
     * @param clasificado
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarEstrategiaComunicacionConocimiento", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarEstrategiaComunicacionConocimiento")
    @ResponseWrapper(localName = "insertarEstrategiaComunicacionConocimientoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarEstrategiaComunicacionConocimientoResponse")
    public String insertarEstrategiaComunicacionConocimiento(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "fechaInicio", targetNamespace = "")
        String fechaInicio,
        @WebParam(name = "lider", targetNamespace = "")
        String lider,
        @WebParam(name = "nombreComunidad", targetNamespace = "")
        String nombreComunidad,
        @WebParam(name = "certificacion", targetNamespace = "")
        boolean certificacion,
        @WebParam(name = "categoria", targetNamespace = "")
        String categoria,
        @WebParam(name = "clasificado", targetNamespace = "")
        boolean clasificado);

    /**
     * 
     * @param estrategiasComunicacion
     * @param codigoGrupo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarEstrategiasComunicacionConocimiento", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarEstrategiasComunicacionConocimiento")
    @ResponseWrapper(localName = "insertarEstrategiasComunicacionConocimientoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarEstrategiasComunicacionConocimientoResponse")
    public String insertarEstrategiasComunicacionConocimiento(
        @WebParam(name = "codigoGrupo", targetNamespace = "")
        String codigoGrupo,
        @WebParam(name = "estrategiasComunicacion", targetNamespace = "")
        List<EstrategiaComunicacionConocimiento> estrategiasComunicacion);

    /**
     * 
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.EstrategiaComunicacionConocimiento>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarEstrategiasComunicacionConocimiento", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarEstrategiasComunicacionConocimiento")
    @ResponseWrapper(localName = "consultarEstrategiasComunicacionConocimientoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarEstrategiasComunicacionConocimientoResponse")
    public List<EstrategiaComunicacionConocimiento> consultarEstrategiasComunicacionConocimiento();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.EstrategiaComunicacionConocimiento>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarEstrategiasComunicacionConocimientoGrupo", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarEstrategiasComunicacionConocimientoGrupo")
    @ResponseWrapper(localName = "consultarEstrategiasComunicacionConocimientoGrupoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarEstrategiasComunicacionConocimientoGrupoResponse")
    public List<EstrategiaComunicacionConocimiento> consultarEstrategiasComunicacionConocimientoGrupo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
