
package co.com.ic2.colciencias.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.productosinvestigacion.InnovacionProcedimientoServicio;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceInnovacionProcedimientoServicio", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.ObjectFactory.class,
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.ws.ObjectFactory.class
})
public interface ServiceInnovacionProcedimientoServicio {


    /**
     * 
     * @param fecha
     * @param certificadoImplementacionM
     * @param codigo
     * @param certificadoImplementacionP
     * @param categoria
     * @param nit
     * @param certificadoImplementacionG
     * @param nombre
     * @param nombreEmpresa
     * @param clasificado
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarInnovacionProcedimientoServicio", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarInnovacionProcedimientoServicio")
    @ResponseWrapper(localName = "insertarInnovacionProcedimientoServicioResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarInnovacionProcedimientoServicioResponse")
    public String insertarInnovacionProcedimientoServicio(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "fecha", targetNamespace = "")
        String fecha,
        @WebParam(name = "nombreEmpresa", targetNamespace = "")
        String nombreEmpresa,
        @WebParam(name = "nit", targetNamespace = "")
        String nit,
        @WebParam(name = "certificadoImplementacionP", targetNamespace = "")
        boolean certificadoImplementacionP,
        @WebParam(name = "certificadoImplementacionM", targetNamespace = "")
        boolean certificadoImplementacionM,
        @WebParam(name = "certificadoImplementacionG", targetNamespace = "")
        boolean certificadoImplementacionG,
        @WebParam(name = "categoria", targetNamespace = "")
        String categoria,
        @WebParam(name = "clasificado", targetNamespace = "")
        boolean clasificado);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarClasificacionInnovacionesProcedimientosServicios", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarClasificacionInnovacionesProcedimientosServicios")
    @ResponseWrapper(localName = "consultarClasificacionInnovacionesProcedimientosServiciosResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarClasificacionInnovacionesProcedimientosServiciosResponse")
    public String consultarClasificacionInnovacionesProcedimientosServicios(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.InnovacionProcedimientoServicio>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarInnovacionesProcedimientosServicios", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarInnovacionesProcedimientosServicios")
    @ResponseWrapper(localName = "consultarInnovacionesProcedimientosServiciosResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarInnovacionesProcedimientosServiciosResponse")
    public List<InnovacionProcedimientoServicio> consultarInnovacionesProcedimientosServicios();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.InnovacionProcedimientoServicio>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarInnovacionesProcedimientosServiciosGrupo", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarInnovacionesProcedimientosServiciosGrupo")
    @ResponseWrapper(localName = "consultarInnovacionesProcedimientosServiciosGrupoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarInnovacionesProcedimientosServiciosGrupoResponse")
    public List<InnovacionProcedimientoServicio> consultarInnovacionesProcedimientosServiciosGrupo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param codigoGrupo
     * @param innovaciones
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarInnovacionesProcedimientosServicios", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarInnovacionesProcedimientosServicios")
    @ResponseWrapper(localName = "insertarInnovacionesProcedimientosServiciosResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarInnovacionesProcedimientosServiciosResponse")
    public String insertarInnovacionesProcedimientosServicios(
        @WebParam(name = "codigoGrupo", targetNamespace = "")
        String codigoGrupo,
        @WebParam(name = "innovaciones", targetNamespace = "")
        List<InnovacionProcedimientoServicio> innovaciones);

}
