
package co.com.ic2.colciencias.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.productosinvestigacion.EmpresaBaseTecnologica;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceEmpresaBaseTecnologica", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.ObjectFactory.class,
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.ws.ObjectFactory.class
})
public interface ServiceEmpresaBaseTecnologica {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.EmpresaBaseTecnologica>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarEmpresasBaseTecnologicaGrupo", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarEmpresasBaseTecnologicaGrupo")
    @ResponseWrapper(localName = "consultarEmpresasBaseTecnologicaGrupoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarEmpresasBaseTecnologicaGrupoResponse")
    public List<EmpresaBaseTecnologica> consultarEmpresasBaseTecnologicaGrupo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.EmpresaBaseTecnologica>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarEmpresasBaseTecnologica", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarEmpresasBaseTecnologica")
    @ResponseWrapper(localName = "consultarEmpresasBaseTecnologicaResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarEmpresasBaseTecnologicaResponse")
    public List<EmpresaBaseTecnologica> consultarEmpresasBaseTecnologica();

    /**
     * 
     * @param codigo
     * @param certificadoCamara
     * @param tipoEmpresa
     * @param tipoIdentificacion
     * @param categoria
     * @param certificacionInstitucional
     * @param numeroTributario
     * @param nombre
     * @param clasificado
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarEmpresaBaseTecnologica", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarEmpresaBaseTecnologica")
    @ResponseWrapper(localName = "insertarEmpresaBaseTecnologicaResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarEmpresaBaseTecnologicaResponse")
    public String insertarEmpresaBaseTecnologica(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "certificadoCamara", targetNamespace = "")
        boolean certificadoCamara,
        @WebParam(name = "numeroTributario", targetNamespace = "")
        String numeroTributario,
        @WebParam(name = "certificacionInstitucional", targetNamespace = "")
        boolean certificacionInstitucional,
        @WebParam(name = "tipoIdentificacion", targetNamespace = "")
        int tipoIdentificacion,
        @WebParam(name = "tipoEmpresa", targetNamespace = "")
        int tipoEmpresa,
        @WebParam(name = "categoria", targetNamespace = "")
        String categoria,
        @WebParam(name = "clasificado", targetNamespace = "")
        boolean clasificado);

    /**
     * 
     * @param empresasBaseTecnologica
     * @param codigoGrupo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarEmpresasBaseTecnologica", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarEmpresasBaseTecnologica")
    @ResponseWrapper(localName = "insertarEmpresasBaseTecnologicaResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarEmpresasBaseTecnologicaResponse")
    public String insertarEmpresasBaseTecnologica(
        @WebParam(name = "codigoGrupo", targetNamespace = "")
        String codigoGrupo,
        @WebParam(name = "empresasBaseTecnologica", targetNamespace = "")
        List<EmpresaBaseTecnologica> empresasBaseTecnologica);

}
