
package co.com.ic2.colciencias.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.productosinvestigacion.ApoyoProgramaFormacion;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceApoyoProgramaFormacion", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.ws.ObjectFactory.class
})
public interface ServiceApoyoProgramaFormacion {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.ApoyoProgramaFormacion>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarApoyoProgramasFormacionGrupo", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarApoyoProgramasFormacionGrupo")
    @ResponseWrapper(localName = "consultarApoyoProgramasFormacionGrupoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarApoyoProgramasFormacionGrupoResponse")
    public List<ApoyoProgramaFormacion> consultarApoyoProgramasFormacionGrupo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarClasificacionApoyoProgramasFormacion", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarClasificacionApoyoProgramasFormacion")
    @ResponseWrapper(localName = "consultarClasificacionApoyoProgramasFormacionResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarClasificacionApoyoProgramasFormacionResponse")
    public String consultarClasificacionApoyoProgramasFormacion(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param codigoGrupo
     * @param apoyosProgramaFormacion
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarApoyosProgramaFormacion", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarApoyosProgramaFormacion")
    @ResponseWrapper(localName = "insertarApoyosProgramaFormacionResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarApoyosProgramaFormacionResponse")
    public String insertarApoyosProgramaFormacion(
        @WebParam(name = "codigoGrupo", targetNamespace = "")
        String codigoGrupo,
        @WebParam(name = "apoyosProgramaFormacion", targetNamespace = "")
        List<ApoyoProgramaFormacion> apoyosProgramaFormacion);

    /**
     * 
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.ApoyoProgramaFormacion>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarApoyoProgramasFormacion", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarApoyoProgramasFormacion")
    @ResponseWrapper(localName = "consultarApoyoProgramasFormacionResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarApoyoProgramasFormacionResponse")
    public List<ApoyoProgramaFormacion> consultarApoyoProgramasFormacion();

    /**
     * 
     * @param fecha
     * @param codigo
     * @param idActoAdministrativo
     * @param numeroActoAdministrativo
     * @param categoria
     * @param institucion
     * @param tipoApoyo
     * @param departamento
     * @param nombre
     * @param clasificado
     * @param facultad
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarApoyoProgramaFormacion", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarApoyoProgramaFormacion")
    @ResponseWrapper(localName = "insertarApoyoProgramaFormacionResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarApoyoProgramaFormacionResponse")
    public String insertarApoyoProgramaFormacion(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "institucion", targetNamespace = "")
        String institucion,
        @WebParam(name = "facultad", targetNamespace = "")
        String facultad,
        @WebParam(name = "departamento", targetNamespace = "")
        String departamento,
        @WebParam(name = "idActoAdministrativo", targetNamespace = "")
        String idActoAdministrativo,
        @WebParam(name = "numeroActoAdministrativo", targetNamespace = "")
        String numeroActoAdministrativo,
        @WebParam(name = "fecha", targetNamespace = "")
        String fecha,
        @WebParam(name = "tipoApoyo", targetNamespace = "")
        String tipoApoyo,
        @WebParam(name = "categoria", targetNamespace = "")
        String categoria,
        @WebParam(name = "clasificado", targetNamespace = "")
        boolean clasificado);

}
