
package co.com.ic2.colciencias.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.productosinvestigacion.InformeTecnicoFinal;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceInformeTecnicoFinal", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.ObjectFactory.class,
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.ws.ObjectFactory.class
})
public interface ServiceInformeTecnicoFinal {


    /**
     * 
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.InformeTecnicoFinal>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarInformesTecnicosFinales", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarInformesTecnicosFinales")
    @ResponseWrapper(localName = "consultarInformesTecnicosFinalesResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarInformesTecnicosFinalesResponse")
    public List<InformeTecnicoFinal> consultarInformesTecnicosFinales();

    /**
     * 
     * @param tituloInvestigacion
     * @param fecha
     * @param codigo
     * @param categoria
     * @param titulo
     * @param certificacionEntidad
     * @param clasificado
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarInformeTecnicoFinal", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarInformeTecnicoFinal")
    @ResponseWrapper(localName = "insertarInformeTecnicoFinalResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarInformeTecnicoFinalResponse")
    public String insertarInformeTecnicoFinal(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "titulo", targetNamespace = "")
        String titulo,
        @WebParam(name = "tituloInvestigacion", targetNamespace = "")
        String tituloInvestigacion,
        @WebParam(name = "fecha", targetNamespace = "")
        String fecha,
        @WebParam(name = "certificacionEntidad", targetNamespace = "")
        boolean certificacionEntidad,
        @WebParam(name = "categoria", targetNamespace = "")
        String categoria,
        @WebParam(name = "clasificado", targetNamespace = "")
        boolean clasificado);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.InformeTecnicoFinal>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarInformesTecnicosFinalesGrupo", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarInformesTecnicosFinalesGrupo")
    @ResponseWrapper(localName = "consultarInformesTecnicosFinalesGrupoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarInformesTecnicosFinalesGrupoResponse")
    public List<InformeTecnicoFinal> consultarInformesTecnicosFinalesGrupo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param informesTecnicos
     * @param codigoGrupo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarInformesTecnicosFinales", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarInformesTecnicosFinales")
    @ResponseWrapper(localName = "insertarInformesTecnicosFinalesResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarInformesTecnicosFinalesResponse")
    public String insertarInformesTecnicosFinales(
        @WebParam(name = "codigoGrupo", targetNamespace = "")
        String codigoGrupo,
        @WebParam(name = "informesTecnicos", targetNamespace = "")
        List<InformeTecnicoFinal> informesTecnicos);

}
