
package co.com.ic2.colciencias.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.productosinvestigacion.ProyectoExtensionCTI;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceProyectoExtensionCTI", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.ws.ObjectFactory.class
})
public interface ServiceProyectoExtensionCTI {


    /**
     * 
     * @param codigoGrupo
     * @param proyectosExtension
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarProyectosExtensionCTI", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarProyectosExtensionCTI")
    @ResponseWrapper(localName = "insertarProyectosExtensionCTIResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarProyectosExtensionCTIResponse")
    public String insertarProyectosExtensionCTI(
        @WebParam(name = "codigoGrupo", targetNamespace = "")
        String codigoGrupo,
        @WebParam(name = "proyectosExtension", targetNamespace = "")
        List<ProyectoExtensionCTI> proyectosExtension);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.ProyectoExtensionCTI>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarProyectosExtensionCTIGrupo", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarProyectosExtensionCTIGrupo")
    @ResponseWrapper(localName = "consultarProyectosExtensionCTIGrupoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarProyectosExtensionCTIGrupoResponse")
    public List<ProyectoExtensionCTI> consultarProyectosExtensionCTIGrupo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.ProyectoExtensionCTI>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarProyectosExtensionCTI", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarProyectosExtensionCTI")
    @ResponseWrapper(localName = "consultarProyectosExtensionCTIResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarProyectosExtensionCTIResponse")
    public List<ProyectoExtensionCTI> consultarProyectosExtensionCTI();

    /**
     * 
     * @param codigo
     * @param fechaInicio
     * @param categoria
     * @param nombreComunidad
     * @param nombre
     * @param fechaFin
     * @param resumenCtel
     * @param clasificado
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarProyectoExtensionCTI", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarProyectoExtensionCTI")
    @ResponseWrapper(localName = "insertarProyectoExtensionCTIResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarProyectoExtensionCTIResponse")
    public String insertarProyectoExtensionCTI(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "fechaInicio", targetNamespace = "")
        String fechaInicio,
        @WebParam(name = "fechaFin", targetNamespace = "")
        String fechaFin,
        @WebParam(name = "nombreComunidad", targetNamespace = "")
        String nombreComunidad,
        @WebParam(name = "resumenCtel", targetNamespace = "")
        String resumenCtel,
        @WebParam(name = "categoria", targetNamespace = "")
        String categoria,
        @WebParam(name = "clasificado", targetNamespace = "")
        boolean clasificado);

}
