
package co.com.ic2.colciencias.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.productosinvestigacion.EstrategiaPedagogicaFomentoCTI;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceEstrategiaPedagogicaFomentoCTI", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.ObjectFactory.class,
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.ws.ObjectFactory.class
})
public interface ServiceEstrategiaPedagogicaFomentoCTI {


    /**
     * 
     * @param codigoGrupo
     * @param estrategiasPedagogicas
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarEstrategiasPedagogicasFomentoCTI", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarEstrategiasPedagogicasFomentoCTI")
    @ResponseWrapper(localName = "insertarEstrategiasPedagogicasFomentoCTIResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarEstrategiasPedagogicasFomentoCTIResponse")
    public String insertarEstrategiasPedagogicasFomentoCTI(
        @WebParam(name = "codigoGrupo", targetNamespace = "")
        String codigoGrupo,
        @WebParam(name = "estrategiasPedagogicas", targetNamespace = "")
        List<EstrategiaPedagogicaFomentoCTI> estrategiasPedagogicas);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.EstrategiaPedagogicaFomentoCTI>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarEstrategiasPedagogicasFomentoCTIGrupo", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarEstrategiasPedagogicasFomentoCTIGrupo")
    @ResponseWrapper(localName = "consultarEstrategiasPedagogicasFomentoCTIGrupoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarEstrategiasPedagogicasFomentoCTIGrupoResponse")
    public List<EstrategiaPedagogicaFomentoCTI> consultarEstrategiasPedagogicasFomentoCTIGrupo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param codigoGrupoInvestigacion
     * @param codigo
     * @param fechaInicio
     * @param categoria
     * @param nombre
     * @param investigadorPrincipal
     * @param certificado
     * @param clasificado
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarEstrategiaPedagogicaFomentoCTI", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarEstrategiaPedagogicaFomentoCTI")
    @ResponseWrapper(localName = "insertarEstrategiaPedagogicaFomentoCTIResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarEstrategiaPedagogicaFomentoCTIResponse")
    public String insertarEstrategiaPedagogicaFomentoCTI(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "fechaInicio", targetNamespace = "")
        String fechaInicio,
        @WebParam(name = "investigadorPrincipal", targetNamespace = "")
        String investigadorPrincipal,
        @WebParam(name = "certificado", targetNamespace = "")
        boolean certificado,
        @WebParam(name = "categoria", targetNamespace = "")
        String categoria,
        @WebParam(name = "clasificado", targetNamespace = "")
        boolean clasificado,
        @WebParam(name = "codigoGrupoInvestigacion", targetNamespace = "")
        boolean codigoGrupoInvestigacion);

    /**
     * 
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.EstrategiaPedagogicaFomentoCTI>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarEstrategiasPedagogicasFomentoCTI", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarEstrategiasPedagogicasFomentoCTI")
    @ResponseWrapper(localName = "consultarEstrategiasPedagogicasFomentoCTIResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarEstrategiasPedagogicasFomentoCTIResponse")
    public List<EstrategiaPedagogicaFomentoCTI> consultarEstrategiasPedagogicasFomentoCTI();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarClasificacionEstrategiasPedagogicasFomentoCTI", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarClasificacionEstrategiasPedagogicasFomentoCTI")
    @ResponseWrapper(localName = "consultarClasificacionEstrategiasPedagogicasFomentoCTIResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarClasificacionEstrategiasPedagogicasFomentoCTIResponse")
    public String consultarClasificacionEstrategiasPedagogicasFomentoCTI(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
