
package co.com.ic2.colciencias.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.productosinvestigacion.EsquemaCircuito;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceEsquemaCiruito", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.ObjectFactory.class,
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.ws.ObjectFactory.class
})
public interface ServiceEsquemaCiruito {


    /**
     * 
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.EsquemaCircuito>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarEsquemasCircuito", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarEsquemasCircuito")
    @ResponseWrapper(localName = "consultarEsquemasCircuitoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarEsquemasCircuitoResponse")
    public List<EsquemaCircuito> consultarEsquemasCircuito();

    /**
     * 
     * @param codigo
     * @param ano
     * @param categoria
     * @param contrato
     * @param numeroRegistro
     * @param tituloRegistro
     * @param paisObtencion
     * @param clasificado
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarEsquemaCircuito", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarEsquemaCircuito")
    @ResponseWrapper(localName = "insertarEsquemaCircuitoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarEsquemaCircuitoResponse")
    public String insertarEsquemaCircuito(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "numeroRegistro", targetNamespace = "")
        String numeroRegistro,
        @WebParam(name = "tituloRegistro", targetNamespace = "")
        String tituloRegistro,
        @WebParam(name = "ano", targetNamespace = "")
        int ano,
        @WebParam(name = "paisObtencion", targetNamespace = "")
        int paisObtencion,
        @WebParam(name = "contrato", targetNamespace = "")
        boolean contrato,
        @WebParam(name = "categoria", targetNamespace = "")
        String categoria,
        @WebParam(name = "clasificado", targetNamespace = "")
        boolean clasificado);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.EsquemaCircuito>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarEsquemasCircuitoGrupo", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarEsquemasCircuitoGrupo")
    @ResponseWrapper(localName = "consultarEsquemasCircuitoGrupoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarEsquemasCircuitoGrupoResponse")
    public List<EsquemaCircuito> consultarEsquemasCircuitoGrupo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param codigoGrupo
     * @param esquemas
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarEsquemasCircuito", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarEsquemasCircuito")
    @ResponseWrapper(localName = "insertarEsquemasCircuitoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarEsquemasCircuitoResponse")
    public String insertarEsquemasCircuito(
        @WebParam(name = "codigoGrupo", targetNamespace = "")
        String codigoGrupo,
        @WebParam(name = "esquemas", targetNamespace = "")
        List<EsquemaCircuito> esquemas);

}
