
package co.com.ic2.colciencias.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceBoletin", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceBoletin {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarBoletines", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarBoletines")
    @ResponseWrapper(localName = "consultarBoletinesResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarBoletinesResponse")
    public String consultarBoletines();

    /**
     * 
     * @param editor
     * @param codigo
     * @param categoria
     * @param institucion
     * @param titulo
     * @param clasificado
     * @param fechaElaboracion
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarBoletin", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarBoletin")
    @ResponseWrapper(localName = "insertarBoletinResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarBoletinResponse")
    public String insertarBoletin(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "titulo", targetNamespace = "")
        String titulo,
        @WebParam(name = "fechaElaboracion", targetNamespace = "")
        String fechaElaboracion,
        @WebParam(name = "editor", targetNamespace = "")
        String editor,
        @WebParam(name = "institucion", targetNamespace = "")
        String institucion,
        @WebParam(name = "categoria", targetNamespace = "")
        String categoria,
        @WebParam(name = "clasificado", targetNamespace = "")
        boolean clasificado);

}
