
package co.com.ic2.colciencias.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.com.ic2.colciencias.gruplac.productosinvestigacion.AsesoriaProgramaOndas;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceAsesoriaProgramaOndas", targetNamespace = "http://ws.colciencias.ic2.com.co/")
@XmlSeeAlso({
    co.com.ic2.colciencias.gruplac.productosinvestigacion.ObjectFactory.class,
    co.com.ic2.colciencias.ws.ObjectFactory.class
})
public interface ServiceAsesoriaProgramaOndas {


    /**
     * 
     * @param asesoriasOndas
     * @param codigoGrupo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarAsesoriasProgramaOndas", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarAsesoriasProgramaOndas")
    @ResponseWrapper(localName = "insertarAsesoriasProgramaOndasResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarAsesoriasProgramaOndasResponse")
    public String insertarAsesoriasProgramaOndas(
        @WebParam(name = "codigoGrupo", targetNamespace = "")
        String codigoGrupo,
        @WebParam(name = "asesoriasOndas", targetNamespace = "")
        List<AsesoriaProgramaOndas> asesoriasOndas);

    /**
     * 
     * @param codigo
     * @param resultados
     * @param registroBD
     * @param municipio
     * @param categoria
     * @param institucion
     * @param departamento
     * @param participacionFerias
     * @param nombre
     * @param reconocido
     * @param clasificado
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarAsesoriaProgramaOndas", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarAsesoriaProgramaOndas")
    @ResponseWrapper(localName = "insertarAsesoriaProgramaOndasResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.InsertarAsesoriaProgramaOndasResponse")
    public String insertarAsesoriaProgramaOndas(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "registroBD", targetNamespace = "")
        String registroBD,
        @WebParam(name = "institucion", targetNamespace = "")
        String institucion,
        @WebParam(name = "municipio", targetNamespace = "")
        String municipio,
        @WebParam(name = "departamento", targetNamespace = "")
        String departamento,
        @WebParam(name = "resultados", targetNamespace = "")
        boolean resultados,
        @WebParam(name = "reconocido", targetNamespace = "")
        boolean reconocido,
        @WebParam(name = "participacionFerias", targetNamespace = "")
        boolean participacionFerias,
        @WebParam(name = "categoria", targetNamespace = "")
        String categoria,
        @WebParam(name = "clasificado", targetNamespace = "")
        boolean clasificado);

    /**
     * 
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.AsesoriaProgramaOndas>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarAsesoriasProgramaOndas", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarAsesoriasProgramaOndas")
    @ResponseWrapper(localName = "consultarAsesoriasProgramaOndasResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarAsesoriasProgramaOndasResponse")
    public List<AsesoriaProgramaOndas> consultarAsesoriasProgramaOndas();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.com.ic2.colciencias.gruplac.productosinvestigacion.AsesoriaProgramaOndas>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarAsesoriasProgramaOndasGrupo", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarAsesoriasProgramaOndasGrupo")
    @ResponseWrapper(localName = "consultarAsesoriasProgramaOndasGrupoResponse", targetNamespace = "http://ws.colciencias.ic2.com.co/", className = "co.com.ic2.colciencias.ws.ConsultarAsesoriasProgramaOndasGrupoResponse")
    public List<AsesoriaProgramaOndas> consultarAsesoriasProgramaOndasGrupo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
